[package]
name = "migration"
version = "0.1.0"
edition = "2024"

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
sea-orm-migration = { version = "1.1.0", features = [
    "runtime-tokio-rustls",
    "sqlx-mysql",
    "sqlx-postgres",
] }
