services:
  emqx-auth-service:
    image: ghcr.io/farismnrr/emqx-auth-service:latest
    container_name: emqx-auth-service
    ports:
      - "5500:5500"
    environment:
      DB_PATH: ${DB_PATH:-/data}
      SECRET_KEY: ${SECRET_KEY}
      API_KEY: ${API_KEY}
      LOG_LEVEL: ${LOG_LEVEL:-info} # Possible values: debug, info, warning, error
    volumes:
      - rocksdb_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5500/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

volumes:
  rocksdb_data:
